//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InsuranceCompany.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Accounting_of_insurance_contractsEntities1 : DbContext
    {
        public Accounting_of_insurance_contractsEntities1()
            : base("name=Accounting_of_insurance_contractsEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CategorySum> CategorySum { get; set; }
        public virtual DbSet<Company> Company { get; set; }
        public virtual DbSet<InsuranceAgent> InsuranceAgent { get; set; }
        public virtual DbSet<InsuranceCase> InsuranceCase { get; set; }
        public virtual DbSet<InsurancePayments> InsurancePayments { get; set; }
        public virtual DbSet<RiskCategory> RiskCategory { get; set; }
        public virtual DbSet<Signature> Signature { get; set; }
        public virtual DbSet<Specialization> Specialization { get; set; }
        public virtual DbSet<Worker> Worker { get; set; }
        public virtual DbSet<Сontract> Сontract { get; set; }
    }
}
