//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InsuranceCompany.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Signature
    {
        public int SignatureId { get; set; }
        public int WorkerId { get; set; }
        public int ContractId { get; set; }
    
        public virtual Worker Worker { get; set; }
        public virtual Сontract Сontract { get; set; }
    }
}
